// Generated by https://quicktype.io

import { IReactions, IUser } from "./issues";

export interface IComment {
  url: string;
  html_url: string;
  issue_url: string;
  id: number;
  node_id: string;
  user: IUser;
  created_at: string;
  updated_at: string;
  author_association: string;
  body: string;
  reactions: IReactions;
  performed_via_github_app: null;
}
